### ISSUE TITLE
Handle condition when prerequisites not installed

### ISSUE THREAD

**Issue by benf-hyperledger** [findas-pty-ltd/BYFN-simple#2]
The ‘byfn-simple.sh’ program contains a check for pre-requisites, the ‘checkPrereqs’ function. This function attempts to invoke some commands to determine their version.

When those commands are not installed, the program displays error messages before continuing.

The ‘checkPrereqs’ function can instead test whether the command is installed, and only then attempt to run it.

**Comment by benf-hyperledger** [comment]
[Merge request 3](https://github.com/findas-pty-ltd/BYFN-simple/pull/3) addresses this by checking whether each command exists before running it.

**Comment by SamCullin** [comment]
Hi Ben I have accepted an edited version of your Merge Request. Great addition.
